name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Zip artifacts for deployment
        run: |
          cd dist/apps/data-api/ && zip ${GITHUB_WORKSPACE}/data-api-release.zip ./* -r
          cd ../../..
          cd dist/apps/stijns-burgers-web/browser && zip ${GITHUB_WORKSPACE}/stijns-burgers-web-release.zip ./* -r
          cd ../../../..
      - name: Upload stijns-burgers-web artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: stijns-burgers-web
          path: stijns-burgers-web-release.zip

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: data-api
          path: data-api-release.zip

  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: stijns-burgers-web

      - name: Unzip artifact for deployment
        run: unzip stijns-burgers-web-release.zip

      - name: Deploy to static azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          app_location: '/' # App source code path
          api_location: '' # Api source code path - optional
          output_location: '' # Built app content directory - optional
        
  deploy-backend-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip

      - name: Install dependencies
        run: npm install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cwfr-stijn-robben'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: "dist/apps/stijns-burgers-web/"
